export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';
export const SELECT_ALL_TAGS = 'SELECT_ALL';
export const DESELECT_ALL_TAGS = 'DESELECT_ALL';
export const SELECT_TAG = 'TOGGLE_TAG';

export const FETCH_SKILLS_REQUEST = 'FETCH_SKILLS_REQUEST';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_FAILURE = 'FETCH_SKILLS_FAILURE';
export const VOTE_FOR_SKILL = 'VOTE_FOR_SKILL';
